### PR TITLE
Ex 2-4

### PR DESCRIPTION
**Pull request by geeezlouise**
Use a for loop to cast integers to strings and cast numbers to float. Count the number of words entered by the user.

### CODE REVIEW

**Comment by mburolla** [comment]
This PR will delete the `requirements.txt` file.  Can you put this file back?

**Comment by geeezlouise** [comment]
I accidently refactored and made a copy of the file. I deleted the copy but I still have the original requirements.txt file in the folder.

**Comment by geeezlouise** [comment]
requirements txt

**Comment by mburolla** [comment]
requirements.txt needs to go in the project root.

**Comment by mburolla** [comment]
It's still showing as deleted in the PR.

**Comment by mburolla** [comment]
A new requirements.txt file has to be created on your computer at the project root:  https://github.com/Cup-Of-JavaScript/Python-Intro-I/blob/dev/requirements.txt

Then push your branch to GitHub and this should fix it.

**Comment by mburolla** [comment]
I don't think you're making any changes.

**Comment by geeezlouise** [comment]
I haven't pushed any updates since the PR. Still working through things on my end.

**Comment by mburolla** [comment]
Nope.  :-)

**Pull request merged**
